### ISSUE TITLE
CSS一些知识点

### ISSUE THREAD

**Issue by Yawytya** [Yawytya/yawytya.github.io#4]
在进行多行文本布局时，当我们要向超出我们预期的文本隐藏起来时，下面的方法是个不错的选择（浏览器版本支不支持记得去[caniuse](https://caniuse.com/)）瞧一瞧)
```css
overflow : hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 2;
-webkit-box-orient: vertical;
```

**Comment by Yawytya** [comment]
去除浮动
```CSS
.clearfix{
  content:'';
  display:block;
  height:0;
  clear:both;
  overflow:hidden;
  visibility:hidden;
}
```
